Troy Mazerolle

Student Number 8972394

# Lab 8 - A Dot product and a Matrix Multiplication in PyTorch and Tensorflow

In [1]:
import torch
import tensorflow as tf

## PyTorch

### Calculate the dot product between two vectors each of length 3

In [2]:
a = torch.tensor([8, 9, 7])
b = torch.tensor([2, 3, 9])
ab_dot_pytorch = a.dot(b)
ab_dot_pytorch

tensor(106)

### Calculate the matrix multiplication of two 2-dimensional matrices, each with a size of (2,2)

In [3]:
c = torch.tensor([[4, 2],
                  [0, 4]])
d = torch.tensor([[7, 7],
                  [3, 3]])
cd_mul_pytorch = c @ d
cd_mul_pytorch

tensor([[34, 34],
        [12, 12]])

## Tensorflow

### Calculate the dot product between the same vectors as above (re-define them in Tensorflow)

In [4]:
a = tf.constant([8, 9, 7])
b = tf.constant([2, 3, 9])
ab_dot_tensorflow = tf.tensordot(a, b, axes = 1)
ab_dot_tensorflow

<tf.Tensor: shape=(), dtype=int32, numpy=106>

### Calculate the matrix multiplication of the same matrics as above (re-define them in Tensorflow)

In [5]:
c = tf.constant([[4, 2],
                 [0, 4]])
d = tf.constant([[7, 7],
                 [3, 3]])
cd_mul_tensorflow = c @ d
cd_mul_tensorflow

<tf.Tensor: shape=(2, 2), dtype=int32, numpy=
array([[34, 34],
       [12, 12]])>